### ISSUE TITLE
friend cant join

### ISSUE THREAD

**Issue by 5ix1t** [beyluta/tf2-server-launcher#5]
when my friend trys to join with the sever IP it says "connection failed after 4 retrys"
if he trys to join through the friends tab in the community severs the server doesnt show up
if he trys to join me through my steam profile he gets the same message as problem 1

**Comment by beyluta** [comment]
Sounds like a networking issue. You need to expose Team Fortress 2's default port to the public by port forwading.

This tutorial is for Minecraft, but the concept is the same for all games. TF2's default port is 27015.
https://www.youtube.com/watch?v=X75GbRaGzu8&ab_channel=TroubleChute

**Comment by 5ix1t** [comment]
> Sounds like a networking issue. You need to expose Team Fortress 2's default port to the public by port forwading.
> 
> This tutorial is for Minecraft, but the concept is the same for all games. TF2's default port is 27015. https://www.youtube.com/watch?v=X75GbRaGzu8&ab_channel=TroubleChute
where can i find the server.properties? (or whatever tf2s version of it is)

**Comment by beyluta** [comment]
> > Sounds like a networking issue. You need to expose Team Fortress 2's default port to the public by port forwading.
> > This tutorial is for Minecraft, but the concept is the same for all games. TF2's default port is 27015. https://www.youtube.com/watch?v=X75GbRaGzu8&ab_channel=TroubleChute
> > where can i find the server.properties? (or whatever tf2s version of it is)

Under `C:\TFGameServers\{YOUR_SERVER_NAME}\config.json` If the port isn't listed there then your port is still set to the default, which is `27015`.

**Comment by 5ix1t** [comment]
> > > Sounds like a networking issue. You need to expose Team Fortress 2's default port to the public by port forwading.
> > > This tutorial is for Minecraft, but the concept is the same for all games. TF2's default port is 27015. https://www.youtube.com/watch?v=X75GbRaGzu8&ab_channel=TroubleChute
> > > where can i find the server.properties? (or whatever tf2s version of it is)
> 
> Under `C:\TFGameServers\{YOUR_SERVER_NAME}\config.json` If the port isn't listed there then your port is still set to the default, which is `27015`.

i cant figure it out the tutorial is to confusing sorry

**Comment by beyluta** [comment]
Do you have access to your router's admin interface? you need the login and password. The ip address is usually `192.168.1.1` (though not always).

1- Go to your Router's interface (http://192.168.1.1)
2- Log in with admin credentails (try "admin" as username and password)
3- Search and click on Port Forwarding
4- Open ports 27015 using TCP and UDP protocols (they are usually called "both")
5- Give your public ip address to your friend along with the port. Example: `172.234.123.244:27015`

If the credentials are wrong, look at the bottom of your router, they usually have the credentials there.
